#!/usr/bin/env php
<?php
/*
    Ulole-Command-Line-Interface
 */

use app\App;
use app\helper\cli\CustomCLI;
use de\interaapps\ulole\core\cli\CLIBootstrapper;
use de\interaapps\ulole\core\Environment;

chdir(".");
require_once "autoload.php";
if (file_exists("vendor/autoload.php"))
    require_once "vendor/autoload.php";

(new App)
    ->setInCLI(true) // Deactivates the web stuff
    ->start(Environment::fromCurrent());

(new CLIBootstrapper($argv))
    ->register(new CustomCLI())
    ->run();