version: '3.3'

services:
  db:
    image: mariadb:latest
    volumes:
      - dbvol:/var/lib/mysql

    environment:
      MYSQL_ROOT_PASSWORD: punyshort
      MYSQL_DATABASE: punyshort
      MYSQL_USER: punyshort
      MYSQL_PASSWORD: punyshort

  backend:
    depends_on:
      - db
    image: interaapps/pastefy-backend:latest
    ports:
      - "81:80"
      
    environment:
      HTTP_SERVER_PORT: 80
      HTTP_SERVER_CORS: "*"
      DATABASE_DRIVER: mysql
      DATABASE_NAME: punyshort
      DATABASE_USER: punyshort
      DATABASE_PASSWORD: punyshort
      DATABASE_HOST: db
      DATABASE_PORT: 3306
      SERVER_NAME: "https://{SERVER}:81"
      OAUTH2_PROVIDER_CLIENT_ID: {CLIENT_ID}
      OAUTH2_PROVIDER_CLIENT_SECRET:

  frontend:
    depends_on:
      - backend
    image: interaapps/pastefy-backend:latest
    ports:
      - "80:80"
      
    environment:
      PUNYSHORT_FRONTEND_API: https://{SERVER}:81
      PUNYSHORT_FRONTEND_CLIENT_ID: CLIENT_ID

  redirect_proxy:
    depends_on:
      - backend
    image: interaapps/punyshort-redirect-proxy:latest
    ports:
      - "83:80"
      
    environment:
      PUNYSHORT_BASE_URL: http://db:81
      PUNYSHORT_KEY: API_KEY
      PUNYSHORT_ERROR_URL: https://{SERVER}:81/error-page
      PUNYSHORT_IP_FORWARDING: true
  

volumes:
  dbvol: